{
 "title": "Crowdsec Insight",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "machine",
    "query": "up{job=~\"crowdsec_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Up since",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "(process_start_time_seconds{machine=\"$machine\"})*1000"
    }
   ]
  },
  {
   "title": "Average Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{machine=\"$machine\"}[$__interval])*100"
    }
   ]
  },
  {
   "title": "Process Max FDs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_max_fds{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Total raw lines",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(cs_reader_hits{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total parsed lines",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Overflows",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflow{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process Open FDs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_open_fds{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Total unparsed lines",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ko{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Top scenarios",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflow{machine=\"$machine\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}