{
 "title": "Crowdsec Details per Machine",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "machine",
    "query": "up{job=~\"crowdsec_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Process Mem Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{machine=\"$machine\"}[$__interval])*100"
    }
   ]
  },
  {
   "title": "Up Since",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "(process_start_time_seconds{machine=\"$machine\"})*1000"
    }
   ]
  },
  {
   "title": "Acquisition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_reader_hits{machine=\"$machine\"}[$__interval])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Parsed lines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok{machine=\"$machine\"}[$__interval])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Unparsed lines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ko{machine=\"$machine\"}[$__interval])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Bucket Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cs_bucket_count{machine=\"$machine\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets creation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_create{machine=\"$machine\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflow{machine=\"$machine\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets underflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_underflow{machine=\"$machine\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}