{
 "title": "Crowdsec Insight",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "machine", "label": "machine", "query": { "query": "label_values(up, machine)" } }
  ]
 },
 "panels": [
  {
   "title": "Up since",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{machine=\"$machine\"})*1000"
    }
   ]
  },
  {
   "title": "Average Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{machine=\"$machine\"}[$__interval])*100"
    }
   ]
  },
  {
   "title": "Process Max FDs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Total raw lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{machine=\"$machine\"}[$__interval]) or up * 0) + sum(increase(cs_cloudwatch_stream_hits_total{machine=\"$machine\"}[$__interval]) or up * 0) + sum(increase(cs_journalctlsource_hits_total{machine=\"$machine\"}[$__interval]) or up * 0) + sum(increase(cs_syslogsource_hits_total{machine=\"$machine\"}[$__interval]) or up * 0)"
    }
   ]
  },
  {
   "title": "Total parsed lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok_total{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Overflows",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process Open FDs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{machine=\"$machine\"}"
    }
   ]
  },
  {
   "title": "Total unparsed lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ko_total{machine=\"$machine\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Top scenarios",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{machine=\"$machine\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}