{
 "title": "Crowdsec Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 }, "options": { "content": "\n# Summary\n\n\n\n" } },
  {
   "title": "Running Crowdsec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"crowdsec_.*\"})"
    }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_journalctlsource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_cloudwatch_stream_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    },
    {
     "expr": "sum(increase(cs_syslogsource_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total[$__interval])) by (machine)",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 13, "x": 0, "y": 18 }, "options": { "content": "\n# Details\n\n\n\n" } },
  {
   "title": "Parsers ok",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_node_hits_ok_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_created_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Parsers nok",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_node_hits_ko_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets Timeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cs_buckets) by (name)", "legendFormat": "{{name}}" }
   ]
  }
 ]
}